// Code generated by entc, DO NOT EDIT.

package ent

import (
	"internal/ent/ent/schema"
	"internal/ent/ent/user"

	"github.com/crossworth/enthstore"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAttributes is the schema descriptor for attributes field.
	userDescAttributes := userFields[0].Descriptor()
	// user.DefaultAttributes holds the default value on creation for the attributes field.
	user.DefaultAttributes = userDescAttributes.Default.(func() enthstore.Hstore)
}
